---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    post:
      summary: creates an user successfully
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                image:
                  type: string
                admin:
                  type: boolean
              required:
              - name
              - email
              - password
  "/auth/login":
    post:
      summary: logs in an existing user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: user logged in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users/{id}":
    delete:
      summary: deletes an existing user
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
